apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: todo
        image: jenkins-python:replaceImageTag
        ports:
        - containerPort: 8000