apiVersion: v1
kind: Service
metadata:
  name: jenkins-python
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 30050 
  selector:
    app: python